import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import NavigationBar from "@/components/nav/NavigationBar";
import "./globals.css";
import { FinanceProvider } from "@/providers/FinanceProvider";

// Font configurations
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
        style={{ fontFamily: "var(--font-inter)" }}
      >
        <NavigationBar />
        <div id="body-container-layout" className="px-3 py-2 w-[100%] mx-auto">
          <FinanceProvider>
              {children}
          </FinanceProvider>
        </div>
      
      </body>
    </html>
  );
}
